projet/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
});

//Compte
Route::get('compte', function () {
    return view('compte/compte');
});

//Commune
Route::get('commune', function () {
    return view('commune/commune');
});


//Activités
Route::get('script_inscription', function () {
    return view('activite/script_inscription');
});

Route::get('script_desinscription', function () {
    return view('activite/script_desinscription');
});

//Associations
Route::get('script_adhesion', function () {
    return view('association/script_adhesion');
});

Route::get('script_desadhesion', function () {
    return view('association/script_desadhesion');
});


use App\Http\Controllers\ActiviteController;
Route::get('activite/{activite?}/inscrit', [ActiviteController::class, 'inscrit'])->name('activite.inscrit');
Route::get('activite/{activite?}/inscription', [ActiviteController::class, 'inscription'])->name('activite.inscription');
Route::get('activite/{activite?}/inscription_admin', [ActiviteController::class, 'inscription_admin'])->name('activite.inscription_admin');
Route::resource('activite', ActiviteController::class);


use App\Http\Controllers\UserController;
Route::get('user/{user?}/enfant', [UserController::class, 'enfant'])->name('user.enfant');
Route::resource('user', UserController::class);


use App\Http\Controllers\EnfantController;
Route::get('enfant/{enfant?}/inscrit', [EnfantController::class, 'inscrit'])->name('enfant.inscrit');
Route::resource('enfant', EnfantController::class);


use App\Http\Controllers\CompteController;
Route::get('compte/compte_enfant/{compte_enfant?}/inscrit', [CompteController::class, 'inscrit'])->name('compte/compte_enfant.inscrit');
Route::resource('compte/compte_enfant', CompteController::class);


use App\Http\Controllers\AssociationController;
Route::get('association/{association?}/activite', [AssociationController::class, 'activite'])->name('association.activite');
Route::get('association/{association?}/adherant', [AssociationController::class, 'adherant'])->name('association.adherant');
Route::resource('association', AssociationController::class);


Route::fallback(function () {
    return view('error');
});


Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('index');
    })->name('/');
});

projet/app/Models/Activite.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Activite extends Model
{
    use HasFactory;
    protected $fillable = [
        'titre',
        'description',
        'dateDebut',
        'dateFin',
        'places',
        'association_id'
    ];

    public function enfants() {
        return $this->belongsToMany(Enfant::class);
    }

    public function association() {
        return $this->belongsTo(Association::class);
    }
}

projet/app/Http/Controllers/ActiviteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Activite;
use App\Models\ActiviteEnfant;
use App\Http\Requests\StoreActiviteRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;


class ActiviteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activiteList = Activite::orderBy('dateDebut', 'desc')->get();
        return view('activite.list', ['activiteList'=>$activiteList]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut === 1) {
                return redirect('/');
            }
        }
        return view('activite.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\StoreActiviteRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreActiviteRequest $request)
    {   
        $request->validated();
        $activite = Activite::create($request->input());
        $activite->save();
    
        return redirect()->route('activite.show', ['activite' => $activite]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('activite.show', ['activite'=> Activite::findorFail($id)]);
    }


    public function inscrit($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut === 1) {
                return redirect('/');
            }
        }
        return view('activite.inscrit', ['activite'=> Activite::findorFail($id)]);
    }


    public function inscription($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
    
            date_default_timezone_set('Europe/Paris');
            $ajd = date( "Y-m-d H:i:s", time());
            $dt = date( "Y-m-d H:i:s", strtotime("+7 day", time()));

            if(Activite::findorFail($id)->dateDebut > $dt) {
                $adhere = 0;
            }

            foreach(Activite::findorFail($id)->association->user as $user)
            if($user->id == Auth::user()->id) {
                $adhere = 1;
            }
            
            if(Activite::findorFail($id)->places <= Activite::findorFail($id)->enfants->count())
            {
                return redirect('/');
            } else {
                if($adhere == 1) {
                    return view('activite.inscription', ['activite'=> Activite::findorFail($id)]);
                } else {
                    return redirect('/');
                }
            }
        }
    }


    public function inscription_admin($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
    
            if (Auth::user()->statut > 2) {

                date_default_timezone_set('Europe/Paris');
                $dt = date( "Y-m-d H:i:s", strtotime("+7 day", time()));
                
                if(Activite::findorFail($id)->places <= Activite::findorFail($id)->enfants->count())
                {
                    return redirect('/');
                } else {

                    if(Activite::findorFail($id)->dateDebut > $dt) {
                        return view('activite.inscription_admin', ['activite'=> Activite::findorFail($id)]);
                    } else {
                        return redirect('/');
                    }

                }
                
            } else {
                return redirect('/');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut === 1) {
                return redirect('/');
            }
        }
        return view('activite.edit', ['activite' => Activite::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreActiviteRequest $request, Activite $activite)
    {
        $request->validated();
        $activite->update($request->input());
        return redirect()->route('activite.show', ['activite' => $activite]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut === 1) {
                return redirect('/');
            } else {
                $activite = Activite::findOrFail($id);
                Schema::rename('activite_enfant', 'activite_enfants');
                ActiviteEnfant::where('activite_id', $activite->id)->delete();
                Schema::rename('activite_enfants', 'activite_enfant');
                $activite->delete();
                return redirect()->route('activite.index');
            }
        }
    }

}

projet/resources/views/activite/create.blade.php
@extends('template')
@section('title') Création d'une activité @endsection
@section('content')
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{url('activite')}}" method="post"> @csrf

  <div class="mb-3 row">
    <label for="titre" class="col-sm-2 col-form-label">Titre</label>

    <div class="col-sm-10">
      <input value="{{ old('titre') }}" type="text" class="form-control @error('titre') is-invalid @enderror" name="titre" id="titre" placeholder="Saisir le titre de l'activité"/>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="description" class="col-sm-2 col-form-label">Description</label>

    <div class="col-sm-10">
      <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3" placeholder="Saisir la description de l'activité">{{ old('description') }}</textarea>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="dateDebut" class="col-sm-2 col-form-label">Date de début</label>

    <div class="col-sm-10">
      <input value="{{ old('dateDebut') }}" type="datetime-local" class="form-control @error('dateDebut') is-invalid @enderror" name="dateDebut" id="dateDebut" placeholder="Saisir la date de début l'activité"/>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="dateFin" class="col-sm-2 col-form-label">Date de fin</label>

    <div class="col-sm-10">
      <input value="{{ old('dateFin') }}" type="datetime-local" class="form-control @error('dateFin') is-invalid @enderror" name="dateFin" id="dateFin" placeholder="Saisir la date de fin de l'activité"/>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="association_id" class="col-sm-2 col-form-label">Association</label>

    <div class="col-sm-10">
    <select class="form-control" name="association_id" id="association_id" placeholder="Saisir l'association">
      <?php
        $associations = DB::select('SELECT * FROM associations');
      ?>
      @foreach($associations as $asso)
        <option value="{{$asso->id}}">{{$asso->nom}}</option>
      @endforeach
    </select>
  </div>
  </div>

  <div class="mb-3 row">
    <label for="places" class="col-sm-2 col-form-label">Nombre de places</label>

    <div class="col-sm-10">
      <input value="{{ old('places') }}" type="number" class="form-control @error('places') is-invalid @enderror" name="places" id="places" min="1" max="999" placeholder="Saisir le nombre de places l'activité"/>
    </div>
  </div>

  
  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">
    <button class="btn btn-success mb-1 mr-1" type="submit">Ajouter</button> &nbsp;

    <a href="{{url('activite')}}" class="btn btn-danger mb-1">Annuler</a>
  </div>

</form>
@endsection

projet/resources/views/activite/edit.blade.php
@extends('template')
@section('title') Modifier une activité @endsection
@section('content')

<div class="modal fade" id="supprimerModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="supprimerModalLabel">Suppression d'une activité</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark">
        Êtes-vous sûr de vouloir supprimer cette activité ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-outline-danger" onclick="javascript:confirmer('{{url('activite/')}}')">Confirmer</button>
      </div>
    </div>
  </div>
</div>
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{url('activite', $activite->id)}}" method="post">
  @csrf
  @method('PUT')
  <div class="mb-3 row">
    <label for="titre" class="col-sm-2 col-form-label">Titre</label>

    <div class="col-sm-10">
      <input type="text" class="form-control" name="titre" id="titre" placeholder="Saisir le titre de l'activité" value="{{$activite->titre}}"/>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="description" class="col-sm-2 col-form-label">Description</label>

    <div class="col-sm-10">
      <textarea class="form-control" id="description" name="description" rows="3" placeholder="Saisir le description de l'activité">{{$activite->description}}</textarea>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="dateDebut" class="col-sm-2 col-form-label">Date de début</label>

    <div class="col-sm-10">
      <input type="datetime-local" class="form-control" name="dateDebut" id="dateDebut" placeholder="Saisir la date de début de l'activité"
             value="{{IntlDateFormatter::formatObject(new DateTime($activite->dateDebut), 'yyyy-MM-dd HH:mm', 'fr') }}"/>
    </div>
  </div>

<div class="mb-3 row">
  <label for="dateFin" class="col-sm-2 col-form-label">Date de fin</label>

  <div class="col-sm-10">
    <input type="datetime-local" class="form-control" name="dateFin" id="dateFin" placeholder="Saisir la date de début de l'activité"
           value="{{IntlDateFormatter::formatObject(new DateTime($activite->dateFin), 'yyyy-MM-dd HH:mm', 'fr') }}"/>
  </div>
</div>

<div class="mb-3 row">
  <label for="association_id" class="col-sm-2 col-form-label">Association</label>

  <div class="col-sm-10">
    <select class="form-control" name="association_id" id="association_id" placeholder="Saisir l'association">
      <?php
        $associations = DB::select('SELECT * FROM associations');
      ?>
      @foreach($associations as $asso)
        <option value="{{$asso->id}}" @if($asso->id === $activite->association_id) selected @endif>{{$asso->nom}}</option>
      @endforeach
    </select>
  </div>
</div>

<div class="mb-3 row">
  <label for="places" class="col-sm-2 col-form-label">Nombre de places</label>

  <div class="col-sm-10">
    <input type="number" class="form-control" name="places" id="places" placeholder="Saisir le nombre de places de l'activité" value="{{$activite->places}}"/>
  </div>
</div>

  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">
      
      <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$activite->id}})" class="btn btn-danger mb-1">
        Supprimer
      </button>  &nbsp; 

      <button class="btn btn-success mb-1 mr-1" type="submit">Enregistrer</button>  &nbsp; 

      <a href="{{ url('activite') }}" class="btn btn-secondary mb-1">Annuler</a>  &nbsp; 

    </div>
  </div>

</form>

<form id="deleteForm" action="" method="POST">
  @method('DELETE')
  @csrf
</form>

</div>
@endsection

@section('head')
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script defer src="{{asset('storage/js/delete.js')}}"></script>
@endsection

projet/resources/views/activite/inscription.blade.php
@extends('template')
@section('title') Inscrire un enfant @endsection
@section('content')
  <h2>
    {{$activite->titre}}
  </h2>
</br>
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{url('script_inscription')}}" method="get"> @csrf

  <div class="mb-3 row">
      <label for="enfant_id" class="col-sm-2 col-form-label">Enfant : </label>
      
      <div class="col-sm-10">
        <select class="form-control" name="enfant_id" id="enfant_id" placeholder="Saisir l'enfant">
        <?php
          $compteur = 0;
          $IdParent = Auth::user()->id;
          $vosEnfants = DB::select("SELECT * FROM enfants WHERE user_id='$IdParent'");
        ?>

        @if(empty($vosEnfants))
          <option disable>Vous n'avez pas enregistré d'enfant</option>
        @else
          @foreach($vosEnfants as $enfant)

            @if(DB::table('activite_enfant')->where('activite_id', $activite->id)->where('enfant_id', $enfant->id)->count() == 0)
              <option value="{{$enfant->id}}">{{$enfant->prenom}} {{$enfant->nom}}</option>
              <?php $compteur++; ?>
            @endif
                    
          @endforeach

          @if($compteur==0)
            <option disable>Tous vos enfants sont déjà inscrit à cette activité</option>
          @endif


        @endif
        </select>
      </div>
  </div>

  <input value="{{$activite->id}}" type="hidden" name="activite_id" id="activite_id"/>
  


  
  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">
      
    @if(empty($vosEnfants))
    <a href="{{route('compte_enfant.create')}}" class="btn btn-block btn-success mb-1">
      Ajouter un enfant
    </a> &nbsp; 
    @else

      @if($compteur != 0)
      <button class="btn btn-success mb-1 mr-1" type="submit">Inscrire</button> &nbsp; 
      @endif

    <a href="{{route('compte_enfant.index')}}" class="btn btn-block btn-secondary mb-1">
      Voir vos enfants
    </a> &nbsp; 
    @endif

    <a href="{{ url('activite') }}" class="btn btn-danger mb-1">Annuler</a>
  </div>

</form>
@endsection

projet/resources/views/activite/inscription_admin.blade.php
@extends('template')
@section('title') Inscrire un enfant @endsection
@section('content')
  <h2>
    {{$activite->titre}}
  </h2>
</br>
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{url('script_inscription')}}" method="get"> @csrf

  <div class="mb-3 row">
      <label for="enfant_id" class="col-sm-2 col-form-label">Enfant : </label>
      
      <div class="col-sm-10">
        <select class="form-control" name="enfant_id" id="enfant_id" placeholder="Saisir l'enfant">
        <?php
          $compteur = 0;
          $lesEnfants = DB::select("SELECT * FROM enfants ORDER BY `user_id` ASC");
          $premierEnfant = current($lesEnfants);
          
        ?>

        @if(empty($lesEnfants))
          <option disable>Il n'y a pas d'enfant d'enregistré</option>
        @else
          @foreach($lesEnfants as $enfant)

            @if(DB::table('activite_enfant')->where('activite_id', $activite->id)->where('enfant_id', $enfant->id)->count() == 0)
                
              <?php
                $user = DB::select("SELECT * FROM users WHERE `id`=$enfant->user_id");
                $parent=current($user);
              ?>

              
              @if(DB::table('association_user')->where('user_id', $parent->id)->where('association_id', $activite->association_id)->count() == 1)
                
                @if($premierEnfant == current($lesEnfants))
                  <option disabled><strong>Parent :  {{$parent->prenom}} {{$parent->nom}} (id : {{$parent->id}})</strong></option>

                  <option value="{{$enfant->id}}"> &nbsp;  &nbsp; - {{$enfant->prenom}} {{$enfant->nom}} (id : {{$enfant->id}})</option>
                  <?php $compteur++; $premierEnfant=$enfant;  ?>
                @else

                  @if($premierEnfant->user_id == $enfant->user_id)
                    <option value="{{$enfant->id}}"> &nbsp;  &nbsp; - {{$enfant->prenom}} {{$enfant->nom}} (id : {{$enfant->id}})</option>
                    <?php $compteur++; ?>
                  @else
                    <option disabled><strong>Parent :  {{$parent->prenom}} {{$parent->nom}} (id : {{$parent->id}})</strong></option>

                    <option value="{{$enfant->id}}"> &nbsp;  &nbsp; - {{$enfant->prenom}} {{$enfant->nom}} (id : {{$enfant->id}})</option>
                    <?php $compteur++; $premierEnfant=$enfant;  ?>
                  @endif

                @endif

              @endif

            @endif
                    
          @endforeach

          @if($compteur==0)
            <option disable>Tous les enfants sont déjà inscrit à cette activité</option>
          @endif


        @endif
        </select>
      </div>
  </div>

  <input value="{{$activite->id}}" type="hidden" name="activite_id" id="activite_id"/>
  


  
  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">

      @if($compteur != 0)
        <button class="btn btn-success mb-1 mr-1" type="submit">Inscrire</button> &nbsp; 
      @endif

    <a href="{{route('enfant.index')}}" class="btn btn-block btn-secondary mb-1">
      Voir les enfants
    </a> &nbsp;

    <a href="{{ url('activite') }}" class="btn btn-danger mb-1">Annuler</a>
  </div>

</form>
@endsection

projet/resources/views/activite/inscrit.blade.php
@extends('template')
@section('title') Enfants inscrits @endsection
@section('content')
<?php
  $compteur = $activite->enfants->count();
  ?>

<strong>{{$activite->titre}}</strong>, 

@if($compteur==$activite->places)
toutes les places sont reservées.
@elseif($compteur==0)
aucun enfant n'est inscrit.
@else
il reste {{$activite->places - $compteur}} places sur {{$activite->places}}. 
@endif

<br/>
<br/>
<ul>
@foreach($activite->enfants as $enfant)
<li>
  <form method="get" action="{{url('script_desinscription')}}">

    <a href="{{route('enfant.show', $enfant->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
    &nbsp; 

    <input type="hidden" name="enfant_id" value="{{$enfant->id}}"/>
    <input type="hidden" name="activite_id" value="{{$activite->id}}"/>
    <input type="hidden" name="page" value="1"/>
    <button class="btn btn-sm btn-danger mb-1" type="submit">
      <i class="bi bi-trash"></i>
    </button>

    &nbsp; 
    {{$enfant->prenom}} 
    {{$enfant->nom}}

  </form> 

</li>
@endforeach
</ul>

<br/>
<br/>


<a href="javascript:window.print()" class="btn btn-block btn-outline-success mb-1">Imprimer</a>  &nbsp; 
<a href="{{route('activite.show', $activite->id)}}" class="btn btn-block btn-light mb-1 text-dark">Retour</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
@endsection

projet/resources/views/activite/show.blade.php
@extends('template')
@section('title') Affichage d'une activité @endsection
@section('content')
<?php
  date_default_timezone_set('Europe/Paris');
  $ajd = date( "Y-m-d H:i:s", time());
  $dt = date( "Y-m-d H:i:s", strtotime("+7 day", time()));
?>
<strong>{{$activite->titre}}</strong>
<br/>
<br/>

Début : <i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateDebut), 'EEEE d MMMM Y', 'fr') }}</i>
à <i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateDebut), 'H', 'fr') }}</i>h 
<i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateDebut), 'm', 'fr') }}</i>.
<br/>

Fin : <i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateFin), 'EEEE d MMMM Y', 'fr') }}</i>
à <i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateFin), 'H', 'fr') }}</i>h 
<i>{{ IntlDateFormatter::formatObject(new DateTime($activite->dateFin), 'm', 'fr') }}</i>.
<br/>
<br/>

Places : {{$activite->places}}.
<br/>
<br/>

<?php
  $compteur=$activite->enfants->count();
  ?>
Inscrits : {{$compteur}}.
<br/>
<br/>

Association : 
<a href="{{route('association.show', $activite->association_id)}}" class="badge rounded-pill bg-secondary" style="text-decoration: none;">
  {{$activite->association->nom}}
</a>
<br/>
<br/>

{{$activite->description}}
<br/>
<br/>
@auth
  @if (Auth::user()->statut > 1)
    <a href="{{route('activite.inscrit', $activite->id)}}" class="btn btn-block btn-warning mb-1">Voir les enfants inscrits</a>  &nbsp; 
    <a href="{{route('activite.edit',$activite->id)}}" class="btn btn-block btn-outline-warning mb-1">Modifier l'activité</i></a>
  @else
    &nbsp; 
  @endif

  @if($activite->dateDebut > $dt)
    <?php
      $adhere = 0;
    ?>
    @foreach($activite->association->user as $user)
      @if($user->id == Auth::user()->id)
        <?php
          $adhere = 1
        ?>
      @endif
    @endforeach

    @if($activite->places <= $activite->enfants->count())
      <br/><br/>
      <p class="btn btn-block btn-secondary mb-1 disabled">Aucune place restante</p>
    @elseif($adhere == 1)
      @if(Auth::user()->statut>2)
        &nbsp; <a href="{{route('activite.inscription_admin', $activite->id)}}" class="btn btn-block btn-outline-danger mb-1">Inscrire un enfant (admin)</a>
      @endif
      <br/><br/>
      <a href="{{route('activite.inscription', $activite->id)}}" class="btn btn-block btn-success mb-1">Inscrire un de vos enfants</a>
    @else
      @if(Auth::user()->statut>2)
        &nbsp; <a href="{{route('activite.inscription_admin', $activite->id)}}" class="btn btn-block btn-outline-danger mb-1">Inscrire un enfant (admin)</a>
      @endif
      <br/><br/>
      <p class="btn btn-block btn-secondary mb-1 disabled">Vous n'adhérez pas</p>
    @endif
  @else
    <br/><br/>
    <p class="btn btn-block btn-secondary mb-1 disabled">Inscriptions fermées</p>
  @endif

&nbsp; 
@endauth
<a href="{{ url('activite') }}" class="btn btn-block btn-secondary mb-1">Retour</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
<a href="javascript:history.go(-1)" class="btn btn-block btn-outline-light mb-1" style="float: right;">Page précédente</a>
@endsection