projet/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
});

//Compte
Route::get('compte', function () {
    return view('compte/compte');
});

//Commune
Route::get('commune', function () {
    return view('commune/commune');
});


//Activités
Route::get('script_inscription', function () {
    return view('activite/script_inscription');
});

Route::get('script_desinscription', function () {
    return view('activite/script_desinscription');
});

//Associations
Route::get('script_adhesion', function () {
    return view('association/script_adhesion');
});

Route::get('script_desadhesion', function () {
    return view('association/script_desadhesion');
});


use App\Http\Controllers\ActiviteController;
Route::get('activite/{activite?}/inscrit', [ActiviteController::class, 'inscrit'])->name('activite.inscrit');
Route::get('activite/{activite?}/inscription', [ActiviteController::class, 'inscription'])->name('activite.inscription');
Route::get('activite/{activite?}/inscription_admin', [ActiviteController::class, 'inscription_admin'])->name('activite.inscription_admin');
Route::resource('activite', ActiviteController::class);


use App\Http\Controllers\UserController;
Route::get('user/{user?}/enfant', [UserController::class, 'enfant'])->name('user.enfant');
Route::resource('user', UserController::class);


use App\Http\Controllers\EnfantController;
Route::get('enfant/{enfant?}/inscrit', [EnfantController::class, 'inscrit'])->name('enfant.inscrit');
Route::resource('enfant', EnfantController::class);


use App\Http\Controllers\CompteController;
Route::get('compte/compte_enfant/{compte_enfant?}/inscrit', [CompteController::class, 'inscrit'])->name('compte/compte_enfant.inscrit');
Route::resource('compte/compte_enfant', CompteController::class);


use App\Http\Controllers\AssociationController;
Route::get('association/{association?}/activite', [AssociationController::class, 'activite'])->name('association.activite');
Route::get('association/{association?}/adherant', [AssociationController::class, 'adherant'])->name('association.adherant');
Route::resource('association', AssociationController::class);


Route::fallback(function () {
    return view('error');
});


Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('index');
    })->name('/');
});

projet/app/Models/Association.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Association extends Model
{
    use HasFactory;
    protected $fillable = [
        'nom'
    ];

    public function activite() {
        return $this->hasMany(Activite::class);
    }

    public function user() {
        return $this->belongsToMany(User::class);
    }
}

projet/app/Http/Controllers/AssociationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Association;
use App\Models\Activite;
use App\Models\ActiviteEnfant;
use App\Models\AssociationUser;
use App\Http\Requests\StoreAssociationRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Schema;


class AssociationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $associationList = Association::orderBy('nom')->get();
        return view('association.list', ['associationList'=>$associationList]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut < 3) {
                return redirect('/');
            }
        }
        return view ('association.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAssociationRequest $request)
    {
        $request->validated();
        $association = Association::create($request->input());
        $association->save();
        return redirect()->route('association.show', ['association'=>$association]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('association.show', ['association' => Association::findOrFail($id)]);
    }


    public function activite($id)
    {
        return view('association.activite', ['association'=> Association::findorFail($id)]);
    }


    public function adherant($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut == 1) {
                return redirect('/');
            }
        }
        return view('association.adherant', ['association'=> Association::findorFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut < 3) {
                return redirect('/');
            }
        }
        return view('association.edit', ['association' => Association::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreAssociationRequest $request, Association $association)
    {
        $request->validated();
        $association->update($request->input());
        return redirect()->route('association.show', ['association' => $association]);
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        }
        else {
            if (Auth::user()->statut < 3) {
                return redirect('/');
            } else {

                $association = Association::findOrFail($id);

                foreach(Activite::where('association_id', $association->id)->get() as $activite) {
                    Schema::rename('activite_enfant', 'activite_enfants');
                    ActiviteEnfant::where('activite_id', $activite->id)->delete();
                    Schema::rename('activite_enfants', 'activite_enfant');
                    $activite->delete();
                }

                Schema::rename('association_user', 'association_users');
                AssociationUser::where('association_id', $association->id)->delete();
                Schema::rename('association_users', 'association_user');

                $association->delete();
                return redirect()->route('association.index');
            }
        }
    }
}

projet/resources/views/association/activite.blade.php
@extends('template')
@section('title') Activités de l'association @endsection
@section('content')
<?php
  $compteur = $association->activite->count();
  ?>

<strong>{{$association->nom}}</strong>,

@if($compteur == 0)
  aucune activité.
@elseif($compteur == 1)
  une seule activité :
@else
  {{$compteur}} activités :
@endif

<br/>
<br/>
<ul>
@foreach($association->activite as $activite)
<li>

  <a href="{{route('activite.show', $activite->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
  &nbsp; 

  &nbsp; 
  {{$activite->titre}}

</li>
@endforeach
</ul>

<br/>
<br/>


<a href="javascript:window.print()" class="btn btn-block btn-outline-success mb-1">Imprimer</a>  &nbsp; 
<a href="{{route('association.show', $association->id)}}" class="btn btn-block btn-light mb-1 text-dark">Retour</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
@endsection

projet/resources/views/association/adherant.blade.php
@extends('template')
@section('title') Adhérants de l'association @endsection
@section('content')
<?php
  $compteur = $association->user->count();
  ?>

<strong>{{$association->nom}}</strong>,

@if($compteur == 0)
  aucune adhérant.
@elseif($compteur == 1)
  un seule adhérant :
@else
  {{$compteur}} adhérants :
@endif

<br/>
<br/>
<ul>
@foreach($association->user as $adherant)
<li>
  <form method="get" action="{{url('script_desadhesion')}}">

    <a href="{{route('user.show', $adherant->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
    &nbsp; 

    <input type="hidden" name="user_id" value="{{$adherant->id}}"/>
    <input type="hidden" name="association_id" value="{{$association->id}}"/>
    <input type="hidden" name="page" value="3"/>
    <button class="btn btn-sm btn-danger mb-1" type="submit">
      <i class="bi bi-trash"></i>
    </button>

    &nbsp; 
    {{$adherant->prenom}} 
    {{$adherant->nom}}

  </form> 

</li>
@endforeach
</ul>

<br/>
<br/>


<a href="javascript:window.print()" class="btn btn-block btn-outline-success mb-1">Imprimer</a>  &nbsp; 
<a href="{{route('association.show', $association->id)}}" class="btn btn-block btn-light mb-1 text-dark">Retour</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
@endsection

projet/resources/views/association/create.blade.php
@extends('template')
@section('title') Ajout d'une association @endsection
@section('content')
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{url('association')}}" method="post"> @csrf

  <div class="mb-3 row">
    <label for="nom" class="col-sm-2 col-form-label">Nom</label>

    <div class="col-sm-10">
      <input value="{{ old('nom') }}" type="text" class="form-control @error('nom') is-invalid @enderror" name="nom" id="nom" placeholder="Saisir le nom de l'association"/>
    </div>
  </div>
 
 

  
  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">
    <button class="btn btn-success mb-1 mr-1" type="submit">Ajouter</button> &nbsp;

    <a href="{{url('association')}}" class="btn btn-danger mb-1">Annuler</a>
  </div>

</form>
@endsection

projet/resources/views/association/edit.blade.php
@extends('template')
@section('title') Modifier une association @endsection
@section('content')

<div class="modal fade" id="supprimerModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="supprimerModalLabel">Suppression d'une association</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark">
        Êtes-vous sûr de vouloir supprimer cette association ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-outline-danger" onclick="confirmer('{{url('association/')}}')">Confirmer</button>
      </div>
    </div>
  </div>
</div>

@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{url('association', $association->id)}}" method="post">
  @csrf
  @method('PUT')
  <div class="mb-3 row">
    <label for="nom" class="col-sm-2 col-form-label">Nom</label>

    <div class="col-sm-10">
      <input type="text" class="form-control @error('nom') is-invalid @enderror" name="nom" id="nom" placeholder="Saisir le nom de l'association" value="{{$association->nom}}" />
    </div>
  </div>
  <div class="mb-3">
    <div class="offset-sm-2 col-sm-10">
      
      <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$association->id}})" class="btn btn-danger mb-1">
        Supprimer
      </button>  &nbsp; 

      <button class="btn btn-success mb-1 mr-1" type="submit">Enregistrer</button>  &nbsp; 

      <a href="{{route('association.index')}}" class="btn btn-secondary mb-1">Annuler</a>
    </div>
  </div>

</form>

<form id="deleteForm" action="" method="POST">
  @method('DELETE')
  @csrf
</form>

</div>
@endsection

@section('head')
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script defer src="{{asset('storage/js/delete.js')}}"></script>
@endsection

projet/resources/views/association/list.blade.php
@extends('template')
@section('title') Liste des associations @endsection
@section('content')

<div class="modal fade" id="supprimerModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="supprimerModalLabel">Suppression d'un association</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark">
        Êtes-vous sûr de vouloir supprimer cette association ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-outline-danger" onclick="javascript:confirmer('{{url('association/')}}')">Confirmer</button>
      </div>
    </div>
  </div>
</div>

<!-- Sélection des associations -->
<?php
  $choix_asso = 1;
  if($_GET) {
    $choix_asso = $_GET['selection_asso'];
  }
?>

<form action="" method="get">
  <div class="mb-3 row">
    <label for="selection_asso" class="col-sm-2 col-form-label">Sélection :</label>

    <div class="col-sm-10">
      <select onchange="this.form.submit()" class="form-control" name="selection_asso" id="selection_asso" style="color: #FFF; background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));">
          <option value="1" @if($choix_asso == 1) selected @endif>Toutes les associations</option>
          @auth
            <option value="2" @if($choix_asso == 2) selected @endif>Seulement les associations auxquelles j'adhère</option>
          @endauth
        </select>
      </div>
  </div>
</form>

<hr/>
<br/>

<!-- Liste des associations -->
<table class="table table-striped-white text-white" id='associationList' style="border-color: white;">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      @auth
        @switch(Auth::user()->statut)
          @case(1)
          @case(2)
            <th scope="col" style="text-align : right;">Actions  &nbsp;  </th>
            @break;
          @default
            <th scope="col" style="text-align : right;">Actions  &nbsp; &nbsp;  &nbsp;  &nbsp;  &nbsp; </th>
            @break;
        @endswitch
      @else
        <th scope="col" style="text-align : right;">Actions</th>
      @endauth
      </tr>
  </thead>
  <tbody>
    
@switch($choix_asso)
  @case(1)
    @foreach($associationList as $association)
      <tr>
        
        <td data-sort="{{$association->nom}}">
          {{$association->nom}}
        </td>
        

        <td style="text-align : right;">
          
          @auth
          
          <?php
            $adhesions = $association->user->pluck('id');
            $adherer = 0;
          ?>

          @foreach($adhesions as $verif)
            @if(Auth::user()->id == $verif)
            <?php
              $adherer=1;
            ?>
            @endif
          @endforeach
          
            @if($adherer == 1)
              <form method="get" action="{{url('script_desadhesion')}}">

                <!--Voir-->
                <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
              
                <input type="hidden" name="association_id" value="{{$association->id}}"/>
                <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
                <input type="hidden" name="page" value="2"/>
                <!--Adherer-->
                <button class="btn btn-sm btn-success mb-1" type="submit">
                  <i class="bi bi-bookmark-check"></i>
                </button>

                @if (Auth::user()->statut == 3)
                <!--Editer-->
                <a href="{{route('association.edit', $association->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

                <!--Supprimer-->
                <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$association->id}})" class="btn btn-sm btn-danger mb-1">
                    <i class="bi bi-trash"></i>
                </button>
                @endif

              </form> 
            @else
              <form method="get" action="{{url('script_adhesion')}}">

                <!--Voir-->
                <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
              
                <input type="hidden" name="association_id" value="{{$association->id}}"/>
                <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
                <input type="hidden" name="page" value="2"/>
                <!--Adherer-->
                <button class="btn btn-sm btn-light mb-1" type="submit">
                  <i class="bi bi-bookmark-plus"></i>
                </button>

                @if (Auth::user()->statut == 3)
                <!--Editer-->
                <a href="{{route('association.edit', $association->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

                <!--Supprimer-->
                <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$association->id}})" class="btn btn-sm btn-danger mb-1">
                    <i class="bi bi-trash"></i>
                </button>
                @endif

              </form> 
            @endif

          @else 
          
            <!--Voir-->
            <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
          
          @endauth
        </td>
        
      </tr>
    @endforeach
    @break

  @case(2)
    @foreach($associationList as $association)

      <?php
        $adhere = 0;
      ?>
      @foreach($association->user as $user)
        @if($user->id == Auth::user()->id)
          <?php
            $adhere = 1
          ?>
        @endif
      @endforeach

      @if($adhere == 1)
        <tr>
          
          <td data-sort="{{$association->nom}}">
            {{$association->nom}}
          </td>
          

          <td style="text-align : right;">
            
            @auth
            
            <?php
              $adhesions = $association->user->pluck('id');
              $adherer = 0;
            ?>

            @foreach($adhesions as $verif)
              @if(Auth::user()->id == $verif)
              <?php
                $adherer=1;
              ?>
              @endif
            @endforeach
            
              @if($adherer == 1)
                <form method="get" action="{{url('script_desadhesion')}}">

                  <!--Voir-->
                  <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
                
                  <input type="hidden" name="association_id" value="{{$association->id}}"/>
                  <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
                  <input type="hidden" name="page" value="2"/>
                  <!--Adherer-->
                  <button class="btn btn-sm btn-success mb-1" type="submit">
                    <i class="bi bi-bookmark-check"></i>
                  </button>

                  @if (Auth::user()->statut == 3)
                  <!--Editer-->
                  <a href="{{route('association.edit', $association->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

                  <!--Supprimer-->
                  <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$association->id}})" class="btn btn-sm btn-danger mb-1">
                      <i class="bi bi-trash"></i>
                  </button>
                  @endif

                </form> 
              @else
                <form method="get" action="{{url('script_adhesion')}}">

                  <!--Voir-->
                  <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
                
                  <input type="hidden" name="association_id" value="{{$association->id}}"/>
                  <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
                  <input type="hidden" name="page" value="2"/>
                  <!--Adherer-->
                  <button class="btn btn-sm btn-light mb-1" type="submit">
                    <i class="bi bi-bookmark-plus"></i>
                  </button>

                  @if (Auth::user()->statut == 3)
                  <!--Editer-->
                  <a href="{{route('association.edit', $association->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

                  <!--Supprimer-->
                  <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$association->id}})" class="btn btn-sm btn-danger mb-1">
                      <i class="bi bi-trash"></i>
                  </button>
                  @endif

                </form> 
              @endif

            @else 
            
              <!--Voir-->
              <a href="{{route('association.show', $association->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
            
            @endauth
          </td>
          
        </tr>
      @endif
    @endforeach
    @break
  
  @endswitch

  </tbody>

</table>
        

<form id="deleteForm" action="" method="POST">
  @method('DELETE')
  @csrf
</form>

  <div class="d-flex justify-content-center">
    @auth
      @if(Auth::user()->statut > 2)
        <a href="{{route('association.create')}}" class="btn btn-block btn-success mb-1">
          Ajouter une nouvelle association
        </a>  &nbsp; &nbsp;
      @endif
    @endauth
    <a href="{{ url('/') }}" class="btn btn-block btn-secondary mb-1">
      Retour
    </a>
</div>
@endsection

@section('head')
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script defer src="{{asset('storage/js/delete.js')}}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<script defer type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<style>
  .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
    color: #FFF;
  }
  .dataTables_wrapper .dataTables_length select {
    color: #FFF;
    background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));
  }
  .dataTables_wrapper .dataTables_filter input {
    color: #FFF;
    background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:active {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current .paginate_button.current:hover {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
    color: #FFF !important;
  }
  table.dataTable thead th, table.dataTable thead td {
    border-bottom: 1px solid rgba(255, 255, 255, 1);;
  }
</style>
@endsection

@section('javascript')

$(document).ready(function (){
        $('#associationList').DataTable({
                "pageLength": 10,
                "language": { "url": "{{ asset('storage/js/french.json') }}" },
                "stateSave": true,
                "columnDefs": [
                  { "targets": [1], "orderable": false, "searchable": false }
                ]
            });
    });

@endsection

projet/resources/views/association/show.blade.php
@extends('template')

@section('title') Affichage d'une association @endsection

@section('content')

    Nom : <strong>{{$association->nom}}</strong>

<br/>
<br/>

@auth
    <?php
        $adhesions = $association->user->pluck('id');
        $adherer = 0;
    ?>

    @foreach($adhesions as $verif)
        @if(Auth::user()->id == $verif)
            <?php
            $adherer=1;
            ?>
        @endif
    @endforeach

    @if($adherer == 1)
    <form method="get" action="{{url('script_desadhesion')}}">

        <input type="hidden" name="association_id" value="{{$association->id}}"/>
        <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
        <input type="hidden" name="page" value="1"/>
        <button class="btn btn-block btn-danger mb-1" type="submit">
            Desadhérer
        </button>&nbsp; 

        <a href="{{route('association.activite', $association->id)}}" class="btn btn-block btn-info mb-1 text-dark">Voir les activités correspondantes</a>&nbsp;

        @if(Auth::user()->statut >= 2)
            <br/> <br/> <a href="{{route('association.adherant', $association->id)}}" class="btn btn-block btn-warning mb-1 text-dark">Voir les adhérants</a>&nbsp; 
            <a href="{{route('association.edit', $association->id)}}" class="btn btn-block btn-outline-warning mb-1">Modifier l'association</a>&nbsp; 
        @endif <br/><br/>
        <a href="{{route('association.index')}}" class="btn btn-block btn-secondary mb-1">Retour</a>&nbsp; 
        <a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
        <a href="javascript:history.go(-1)" class="btn btn-block btn-outline-light mb-1" style="float: right;">Page précédente</a>

    </form> 

    @else
    <form method="get" action="{{url('script_adhesion')}}">

        <input type="hidden" name="association_id" value="{{$association->id}}"/>
        <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>
        <input type="hidden" name="page" value="1"/>
        <button class="btn btn-block btn-success mb-1" type="submit">
            Adhérer
        </button>&nbsp;

        <a href="{{route('association.activite', $association->id)}}" class="btn btn-block btn-info mb-1 text-dark">Voir les activités correspondantes</a>&nbsp;

        @if(Auth::user()->statut >= 2)
            <br/><br/><a href="{{route('association.adherant', $association->id)}}" class="btn btn-block btn-warning mb-1 text-dark">Voir les adhérants</a>&nbsp; 
            <a href="{{route('association.edit', $association->id)}}" class="btn btn-block btn-outline-warning mb-1">Modifier l'association</a>&nbsp; 
        @endif <br/><br/>
        <a href="{{route('association.index')}}" class="btn btn-block btn-secondary mb-1">Retour</a>&nbsp; 
        <a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
        <a href="javascript:history.go(-1)" class="btn btn-block btn-outline-light mb-1" style="float: right;">Page précédente</a>

    </form> 
    @endif

@else
    <a href="{{route('association.activite', $association->id)}}" class="btn btn-block btn-info mb-1 text-dark">Voir les activités correspondantes</a>&nbsp; 
    <a href="{{route('association.index')}}" class="btn btn-block btn-secondary mb-1">Retour</a>&nbsp; 
    <a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
    <a href="javascript:history.go(-1)" class="btn btn-block btn-outline-light mb-1" style="float: right;">Page précédente</a>
@endauth

@endsection