projet/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
});

//Compte
Route::get('compte', function () {
    return view('compte/compte');
});

//Commune
Route::get('commune', function () {
    return view('commune/commune');
});


//Activités
Route::get('script_inscription', function () {
    return view('activite/script_inscription');
});

Route::get('script_desinscription', function () {
    return view('activite/script_desinscription');
});

//Associations
Route::get('script_adhesion', function () {
    return view('association/script_adhesion');
});

Route::get('script_desadhesion', function () {
    return view('association/script_desadhesion');
});


use App\Http\Controllers\ActiviteController;
Route::get('activite/{activite?}/inscrit', [ActiviteController::class, 'inscrit'])->name('activite.inscrit');
Route::get('activite/{activite?}/inscription', [ActiviteController::class, 'inscription'])->name('activite.inscription');
Route::get('activite/{activite?}/inscription_admin', [ActiviteController::class, 'inscription_admin'])->name('activite.inscription_admin');
Route::resource('activite', ActiviteController::class);


use App\Http\Controllers\UserController;
Route::get('user/{user?}/enfant', [UserController::class, 'enfant'])->name('user.enfant');
Route::resource('user', UserController::class);


use App\Http\Controllers\EnfantController;
Route::get('enfant/{enfant?}/inscrit', [EnfantController::class, 'inscrit'])->name('enfant.inscrit');
Route::resource('enfant', EnfantController::class);


use App\Http\Controllers\CompteController;
Route::get('compte/compte_enfant/{compte_enfant?}/inscrit', [CompteController::class, 'inscrit'])->name('compte/compte_enfant.inscrit');
Route::resource('compte/compte_enfant', CompteController::class);


use App\Http\Controllers\AssociationController;
Route::get('association/{association?}/activite', [AssociationController::class, 'activite'])->name('association.activite');
Route::get('association/{association?}/adherant', [AssociationController::class, 'adherant'])->name('association.adherant');
Route::resource('association', AssociationController::class);


Route::fallback(function () {
    return view('error');
});


Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('index');
    })->name('/');
});

projet/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'prenom',
        'email',
        'password',
        'nom',
        'pseudonyme',
        'statut'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];


    public function enfant() {
        return $this->hasMany(Enfant::class);
    }

    public function association() {
        return $this->belongsToMany(Association::class);
    }
}

projet/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Enfant;
use App\Models\ActiviteEnfant;
use App\Models\AssociationUser;
use App\Http\Requests\StoreUserRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
            if (Auth::user()->statut == 1) {
                return redirect('/');
            } else {
                $userList = User::orderBy('prenom')->get();
                return view('user.list', ['userList'=>$userList]);
            }
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Pas de create user.
        return redirect('/');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'prenom' => ['required'],
            'nom' => ['required'],
            'pseudonyme'=>['required'],
            'statut'=>['required'],
            'email'=>['required']
          ]);
          $user->save();
          return redirect()->route('user.show', ['user' => $user]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
            if (Auth::user()->statut == 1) {
                return redirect('/');
            } 
        }
        return view('user.show', ['user' => User::findOrFail($id)]);
    }
    

    public function enfant($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
            if (Auth::user()->statut == 1) {
                return redirect('/');
            }
        } 
        return view('user.enfant', ['user'=> User::findorFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
            if (Auth::user()->statut !== 3) {
                return redirect('/');
            } 
        }
        return view('user.edit', ['user' => User::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUserRequest $request, User $user)
    {
        $request->validated();
        $user->update($request->input());
        return redirect()->route('user.show', ['user' => $user]);
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!Auth::check()) {
            return redirect('login');
        } else {
            if (Auth::user()->statut !== 3) {
                return redirect('/');
            } else {
                $user = User::findOrFail($id);

                //Supprimer les enfants et leurs inscriptions
                Schema::rename('activite_enfant', 'activite_enfants');
                foreach(Enfant::where('user_id', $user->id)->get() as $enfant) {
                    ActiviteEnfant::where('enfant_id', $enfant->id)->delete();
                    $enfant->delete();
                }
                Schema::rename('activite_enfants', 'activite_enfant');

                //Supprimer les adhesions
                Schema::rename('association_user', 'association_users');
                AssociationUser::where('user_id', $user->id)->delete();
                Schema::rename('association_users', 'association_user');

                //Supprimer l'utilisateur
                $user->delete();
                return redirect()->route('user.index');
            }
        }
        
    }
}

projet/resources/views/user/edit.blade.php
@extends('template')
@section('title') Modifier un utilisateur @endsection
@section('content')

<div class="modal fade" id="supprimerModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="supprimerModalLabel">Suppression d'un utilisateur</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark">
        Êtes-vous sûr de vouloir supprimer cet utilisateur ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-outline-danger" onclick="confirmer('{{url('user/')}}')">Confirmer</button>
      </div>
    </div>
  </div>
</div>

@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{url('user', $user->id)}}" method="post">
  @csrf
  @method('PUT')
  <div class="mb-3 row">
    <label for="titre" class="col-sm-2 col-form-label">Pseudonyme</label>

    <div class="col-sm-10">
      <input type="text" class="form-control" name="pseudonyme" id="pseudonyme" placeholder="Saisir le pseudo de l'utilisateur" value="{{$user->pseudonyme}}"/>
    </div>
  </div>

  <div class="mb-3 row">
    <label for="prenom" class="col-sm-2 col-form-label">Prénom</label>

    <div class="col-sm-10">
      <textarea class="form-control" id="prenom" name="prenom" rows="3" placeholder="Saisir le prenom de l'utilisateur">{{$user->prenom}}</textarea>
    </div>
  </div>
  <div class="mb-3 row">
    <label for="nom" class="col-sm-2 col-form-label">Nom</label>

    <div class="col-sm-10">
      <textarea class="form-control" id="nom" name="nom" rows="3" placeholder="Saisir le nom de l'utilisateur">{{$user->nom}}</textarea>
    </div>
  </div>
  <div class="mb-3 row">
    <label for="email" class="col-sm-2 col-form-label">Adresse Email</label>

    <div class="col-sm-10">
      <textarea class="form-control" id="email" name="email" rows="3" placeholder="Saisir l'adresse Email de l'utilisateur">{{$user->email}}</textarea>
    </div>
  </div>

<div class="mb-3 row">
  <label for="statut" class="col-sm-2 col-form-label">Statut de l'utilisateur</label>

  <div class="col-sm-10">
    <select class="form-control" name="statut" id="statut" placeholder="Saisir le statut de l'utilisateur">
      <option value="1" @if($user->statut === 1) selected @endif>Utilisateur</option>
      <option value="2" @if($user->statut === 2) selected @endif>Gestionnaire</option>
      <option value="3" @if($user->statut === 3) selected @endif>Administrateur</option>
    </select>
  </div>
</div>


<div class="mb-3">
  <div class="offset-sm-2 col-sm-10">

    <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$user->id}})" class="btn btn-danger mb-1">
      Supprimer
    </button>  &nbsp; 

    <button class="btn btn-success mb-1 mr-1" type="submit">Enregistrer</button>  &nbsp; 

    <a href="{{route('user.index')}}" class="btn btn-secondary mb-1">Annuler</a>
  </div>
</div>

</form>

<form id="deleteForm" action="" method="POST">
  @method('DELETE')
  @csrf
</form>

</div>
@endsection

@section('head')
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script defer src="{{asset('storage/js/delete.js')}}"></script>
@endsection

projet/resources/views/user/enfant.blade.php
@extends('template')
@section('title') Enfants de l'utilisateur @endsection
@section('content')
<?php
  $compteur = $user->enfant->count();
  ?>

<strong>{{$user->nom}} {{$user->prenom}}</strong>, 

@if($compteur == 1)
a un seul enfant.
@elseif($compteur==0)
n'a aucun enfant.
@else
a {{$compteur}} enfants.
@endif

<br/>
<br/>
<ul>
    <form id="deleteForm" action="" method="POST">
      @method('DELETE')
      @csrf
    </form>
@foreach($user->enfant as $enfant)
<li>
  <a href="{{route('enfant.show', $enfant->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>
  &nbsp; 

  @if(Auth::user()->statut >2)
    <!--Supprimer-->
    <button type="submit" formaction="{{route('enfant.destroy', $enfant->id)}}" form="deleteForm" class="btn btn-sm btn-danger mb-1">
      <i class="bi bi-trash"></i>
    </button>
  @endif

  &nbsp; 
  {{$enfant->nom}} 
  {{$enfant->prenom}}
</li>
@endforeach
</ul>
   

<br/>
<br/>


<a href="javascript:window.print()" class="btn btn-block btn-outline-success mb-1">Imprimer</a>  &nbsp; 
<a href="{{route('user.show', $user->id)}}" class="btn btn-block btn-light mb-1 text-dark">Retour</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
@endsection

projet/resources/views/user/list.blade.php
@extends('template')
@section('title') Liste des utilisateurs @endsection
@section('content')

<div class="modal fade" id="supprimerModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="supprimerModalLabel">Suppression d'un utilisateur</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark">
        Êtes-vous sûr de vouloir supprimer cet utilisateur ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-outline-danger" onclick="confirmer('{{url('user/')}}')">Confirmer</button>
      </div>
    </div>
  </div>
</div>

<!-- Sélection des utilisateurs -->
<?php
  $choix_user = 1;
  if($_GET) {
    $choix_user = $_GET['selection_user'];
  }
?>

  <form action="" method="get">
    <div class="mb-3 row">
      <label for="selection_user" class="col-sm-2 col-form-label">Sélection :</label>

      <div class="col-sm-10">
        <select onchange="this.form.submit()" class="form-control" name="selection_user" id="selection_user" style="color: #FFF; background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));">
            <option value="1" @if($choix_user == 1) selected @endif>Tous les utilisateurs</option>
            <option value="2" @if($choix_user == 2) selected @endif>Seulement les utilisateurs normaux</option>
            <option value="3" @if($choix_user == 3) selected @endif>Seulement les gestionnaires</option>
            <option value="4" @if($choix_user == 4) selected @endif>Seulement les administrateurs</option>
          </select>
        </div>
    </div>
  </form>

<hr/>
<br/>

<!-- Liste des utilisateurs -->
<table class="table table-striped-white text-white" id='userList' style="border-color: white;">
  <thead>
    <tr>
      <th scope="col">Pseudonyme</th>
      <th scope="col">Prenom</th>
      <th scope="col">Nom</th>
      <th scope="col">Email</th>
      <th scope="col">Statut</th>
      @if(Auth::user()->statut == 3)
        <th scope="col" style="text-align : right;">Actions  &nbsp;  &nbsp;  &nbsp; </th>
      @else
        <th scope="col" style="text-align : right;">Actions</th>
      @endif
      </tr>
  </thead>
  <tbody>


@switch($choix_user)
  @case(1)
    @foreach($userList as $user)
      <tr>
        
        <td data-sort="{{$user->pseudonyme}}">
          <strong>{{$user->pseudonyme}}</strong>
        </td>

        <td data-sort="{{$user->prenom}}">
          {{$user->prenom}}
        </td>

        <td data-sort="{{$user->nom}}">
          {{$user->nom}}
        </td>

        <td data-sort="{{$user->email}}">
          {{$user->email}}
        </td>
        
        <td data-sort="{{$user->statut}}">
          @if($user->statut === 1)
            <i>Utilisateur</i>
          @elseif($user->statut === 2)
            <i>Gestionnaire</i>
          @else
            <i>Administrateur</i>
          @endif
        </td>

        <td style="text-align : right;">
          <!--Voir-->
          <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>

          @auth
            @if (Auth::user()->statut > 2)
              <!--Editer-->
              <a href="{{route('user.edit', $user->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

              <!--Supprimer-->
              <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$user->id}})" class="btn btn-sm btn-danger mb-1">
                <i class="bi bi-trash"></i>
              </button>
            @endif
          @endauth
        </td>
      </tr>
    @endforeach
    @break

    @case(2)
    @foreach($userList as $user)
      @if($user->statut == 1)
        <tr>
          
          <td data-sort="{{$user->pseudonyme}}">
            <strong>{{$user->pseudonyme}}</strong>
          </td>

          <td data-sort="{{$user->prenom}}">
            {{$user->prenom}}
          </td>

          <td data-sort="{{$user->nom}}">
            {{$user->nom}}
          </td>

          <td data-sort="{{$user->email}}">
            {{$user->email}}
          </td>
          
          <td data-sort="{{$user->statut}}">
            @if($user->statut === 1)
              <i>Utilisateur</i>
            @elseif($user->statut === 2)
              <i>Gestionnaire</i>
            @else
              <i>Administrateur</i>
            @endif
          </td>

          <td style="text-align : right;">
            <!--Voir-->
            <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>

            @auth
              @if (Auth::user()->statut > 2)
                <!--Editer-->
                <a href="{{route('user.edit', $user->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

                <!--Supprimer-->
                <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$user->id}})" class="btn btn-sm btn-danger mb-1">
                  <i class="bi bi-trash"></i>
                </button>
              @endif
            @endauth
          </td>
        </tr>
        @endif
    @endforeach
    @break

@case(3)
@foreach($userList as $user)
  @if($user->statut == 2)
    <tr>
      
      <td data-sort="{{$user->pseudonyme}}">
        <strong>{{$user->pseudonyme}}</strong>
      </td>

      <td data-sort="{{$user->prenom}}">
        {{$user->prenom}}
      </td>

      <td data-sort="{{$user->nom}}">
        {{$user->nom}}
      </td>

      <td data-sort="{{$user->email}}">
        {{$user->email}}
      </td>
      
      <td data-sort="{{$user->statut}}">
        @if($user->statut === 1)
          <i>Utilisateur</i>
        @elseif($user->statut === 2)
          <i>Gestionnaire</i>
        @else
          <i>Administrateur</i>
        @endif
      </td>

      <td style="text-align : right;">
        <!--Voir-->
        <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>

        @auth
          @if (Auth::user()->statut > 2)
            <!--Editer-->
            <a href="{{route('user.edit', $user->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

            <!--Supprimer-->
            <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$user->id}})" class="btn btn-sm btn-danger mb-1">
              <i class="bi bi-trash"></i>
            </button>
          @endif
        @endauth
      </td>
    </tr>
    @endif
  @endforeach
  @break

@case(4)
@foreach($userList as $user)
  @if($user->statut == 3)
    <tr>
      
      <td data-sort="{{$user->pseudonyme}}">
        <strong>{{$user->pseudonyme}}</strong>
      </td>

      <td data-sort="{{$user->prenom}}">
        {{$user->prenom}}
      </td>

      <td data-sort="{{$user->nom}}">
        {{$user->nom}}
      </td>

      <td data-sort="{{$user->email}}">
        {{$user->email}}
      </td>
      
      <td data-sort="{{$user->statut}}">
        @if($user->statut === 1)
          <i>Utilisateur</i>
        @elseif($user->statut === 2)
          <i>Gestionnaire</i>
        @else
          <i>Administrateur</i>
        @endif
      </td>

      <td style="text-align : right;">
        <!--Voir-->
        <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-info mb-1"><i class="bi bi-eye"></i></a>

        @auth
          @if (Auth::user()->statut > 2)
            <!--Editer-->
            <a href="{{route('user.edit', $user->id)}}" class="btn btn-sm btn-warning mb-1"><i class="bi bi-pencil-square"></i></a>

            <!--Supprimer-->
            <button type="button" data-bs-toggle="modal" data-bs-target="#supprimerModal" onclick="supprimer({{$user->id}})" class="btn btn-sm btn-danger mb-1">
              <i class="bi bi-trash"></i>
            </button>
          @endif
        @endauth
      </td>
    </tr>
    @endif
  @endforeach
  @break

  @endswitch

  </tbody>

</table>

<form id="deleteForm" action="" method="POST">
  @method('DELETE')
  @csrf
</form>

  <div class="d-flex justify-content-center">

  <a href="{{ url('/') }}" class="btn btn-block btn-secondary mb-1">
    Retour
  </a>

</div>
@endsection

@section('head')
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script defer src="{{asset('storage/js/delete.js')}}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<script defer type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<style>
  .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
    color: #FFF;
  }
  .dataTables_wrapper .dataTables_length select {
    color: #FFF;
    background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));
  }
  .dataTables_wrapper .dataTables_filter input {
    color: #FFF;
    background-color:  rgba(var(--bs-dark-rgb),var(--bs-bg-opacity));
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:active {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current .paginate_button.current:hover {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button {
    color: #FFF !important;
  }
  .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
    color: #FFF !important;
  }
  table.dataTable thead th, table.dataTable thead td {
    border-bottom: 1px solid rgba(255, 255, 255, 1);;
  }
</style>
@endsection

@section('javascript')

$(document).ready(function (){
        $('#userList').DataTable({
                "pageLength": 10,
                "language": { "url": "{{ asset('storage/js/french.json') }}" },
                "stateSave": true,
                "columnDefs": [
                  { "targets": [5], "orderable": false, "searchable": false }
                ]
            });
    });

@endsection

projet/resources/views/user/show.blade.php
@extends('template')
@section('title') Affichage d'un utilsateur @endsection
@section('content')
<strong>{{$user->pseudonyme}}</strong>
<br/>
<br/>
Email : {{$user->email}}
<br/>
<br/>
Prénom : {{$user->prenom}}
<br/>
Nom : {{$user->nom}}
<br/>
<br/>
<i>Statut ({{$user->statut}}) :
    @if($user->statut === 1)
        Utilisateur
    @elseif($user->statut === 2)
        Gestionnaire
    @else
        Administrateur
    @endif
</i>
<br/>
<br/>
<a href="{{route('user.enfant', $user->id)}}" class="btn btn-block btn-warning mb-1 text-dark">Voir ses enfants</a>  &nbsp; 
<a href="{{url('user/')}}" class="btn btn-block btn-light mb-1 text-dark">Retour à la liste</a>  &nbsp; 
<a href="{{url('/')}}" class="btn btn-block btn-outline-light mb-1">Accueil</a>
          <a href="javascript:history.go(-1)" class="btn btn-block btn-outline-light mb-1" style="float: right;">Page précédente</a>
@endsection